package Core.Exception.ThrowCustomException;

/*
Try this problem after doing ThrowsException. CustomExceptionThrower should throw CustomException.
 */
public class CustomException extends Exception{
}
